//actions
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const TOGGLE_PROFILE_OPTIONS = "TOGGLE_PROFILE_OPTIONS";

export const SIGNING_IN = "SIGNING_IN";

export const USER_SIGNED_IN = "USER_SIGNED_IN";
