//actions
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const TOGGLE_PROFILE_OPTIONS = "TOGGLE_PROFILE_OPTIONS";

export const SIGNING_IN = "SIGNING_IN";

export const USER_SIGNED_IN = "USER_SIGNED_IN";

export const LOGOUT_USER = "LOGOUT_USER";

export const TOGGLE_CREATING_ACCOUNT = "TOGGLE_CREATING_ACCOUNT";

export const CREATE_USER_ERRORS = {
  PASSWORD_MISMATCH: "CREATE_USER_PASSWORD_MISMATCH",
  INVALID_USERNAME: "CREATE_USER_INVALID_USERNAME",
  USERNAME_TAKEN: "CREATE_USER_USERNAME_TAKEN"
};

export const LOADING_COURSES = "LOADING_COURSES";

export const LOADED_COURSES = "LOADED_COURSES";
